void dir_a( char *dir_name, int no, int *arr, int mode );
void dir_d( char *dir_name, int no, int *arr );
void dir_L( char *dir_name, int no, int *arr, int level );
void dir_p( char *dir_name, int no, int *arr, int mode );
void dir_u( char *dir_name, int no, int *arr, int mode );
void dir_i( char *dir_name, int no );
void dir_S( char *dir_name, int no );
void dir_n( char *dir_name, int no, int *arr );
void dir_X( char *dir_name, int no );
void dir_J( char *dir_name, int no );
void dir_P( char *dir_name, int no, int *arr, int mode, char *patt );
void help();
void version();